name: $(Date:yyyyMMdd).$(Rev:.r)

trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - Source/*
      - Plugins/*
      - Content/*
      - /*.uproject

variables:
    - name:  Pipeline.GameProjectRoot
      value: '.'


# ==================settable variable at queue time=============
#   PipelineInput.bCleanSCM: true

resources:
  repositories:
    - repository: templates
      type: git
      name: UEHorizonBuildScript/azure-pipelines-template

# verify-plugin-build
jobs:
    #- ${ if eq(variables['Pipeline.bBuildWin64'], 'true') }:

    - template: job/verify-plugin-build.yml@templates

    - template: job/upload-sonarqube.yml@templates
      parameters:
          name: 'Upload_SonarQube'
          group: 'ue4-build-var-win-group'
          pool: 'Default'
          platform: 'win64'
          # dependsOn:
          #   - 'Build_Win64_Standalone'
 